final fix

diff --git a/.github/workflows/reuseble_agd.yml b/.github/workflows/reuseble_agd.yml
--- a/.github/workflows/reuseble_agd.yml
+++ b/.github/workflows/reuseble_agd.yml
@@ -37,7 +37,7 @@ jobs:
       - name: Copy logs to a new file
         continue-on-error: true
         run: |
-          cat .auto_doc_cache/report.log > agd_report.log || echo "Logs not found"
+          cat .auto_doc_cache/report.txt > agd_report.txt || echo "Logs not found"
 
       - name: Commit and Push changes
         run: |
