test

diff --git a/.github/workflows/reuseble_agd.yml b/.github/workflows/reuseble_agd.yml
--- a/.github/workflows/reuseble_agd.yml
+++ b/.github/workflows/reuseble_agd.yml
@@ -37,7 +37,7 @@ jobs:
           TERM: "xterm-256color"  
 
       - name: Copy output to README
-        run: cat .auto_doc_cache/output_doc.md > README.md
+        run: cat .auto_doc_cache/output_doc.md > README.md || echo "doc not found"
 
       - name: Copy logs to a new file
         continue-on-error: true
